'use server';

/**
 * @fileOverview An AI agent to generate initial tags for an image.
 *
 * - generateInitialTags - A function that handles the tag generation process.
 * - GenerateInitialTagsInput - The input type for the generateInitialTags function.
 * - GenerateInitialTagsOutput - The return type for the generateInitialTags function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateInitialTagsInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo to generate tags for, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type GenerateInitialTagsInput = z.infer<typeof GenerateInitialTagsInputSchema>;

const GenerateInitialTagsOutputSchema = z.object({
  tags: z.array(z.string()).describe('An array of tags generated by the AI.'),
});
export type GenerateInitialTagsOutput = z.infer<typeof GenerateInitialTagsOutputSchema>;

export async function generateInitialTags(input: GenerateInitialTagsInput): Promise<GenerateInitialTagsOutput> {
  return generateInitialTagsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateInitialTagsPrompt',
  input: {schema: GenerateInitialTagsInputSchema},
  output: {schema: GenerateInitialTagsOutputSchema},
  prompt: `You are an AI that generates relevant tags for an image.

  Given the following image, generate a list of tags that describe the image.

  Image: {{media url=photoDataUri}}
  Tags:`, // Ensure the LLM knows to return tags
});

const generateInitialTagsFlow = ai.defineFlow(
  {
    name: 'generateInitialTagsFlow',
    inputSchema: GenerateInitialTagsInputSchema,
    outputSchema: GenerateInitialTagsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
