/**
 * @fileOverview Defines the TypeScript types for the traffic analysis data structure.
 * This ensures type safety between the backend response and the frontend components.
 */

/**
 * Defines the structure for the 'semantic_search' part of the analysis.
 * This is optimized for natural language queries and keyword filtering.
 */
export interface SemanticSearch {
  /**
   * A dense, coherent, and detailed natural language description of the image.
   * It integrates time, location, weather, infrastructure, and OCR information.
   * This description is intended to be vectorized for similarity search.
   */
  description: string;

  /**
   * An array of 10-15 core keywords covering the scene, facilities, weather, and specific objects.
   */
  keywords: string[];
}

/**
 * Defines the structure for the 'training_data' part of the analysis.
 * This is tailored for machine learning model training pipelines (e.g., CLIP, YOLO).
 */
export interface TrainingData {
  /**


  /**
   * An array of Qwen model generated captions or a structured dictionary.
   * These are more detailed and contextual descriptions generated by the Qwen model.
   */
  qwen_captions: Record<string, any> | string[];

  /**
   * A structured list of detected objects in the format "color-object-state/position".
   * e.g., "黑色-轿车-中间车道". Useful for object detection model training (like YOLO).
   */
  yolo_objects: string[];
}

/**
 * The main interface for the entire traffic analysis JSON output.
 */
export interface TrafficAnalysisOutput {
  semantic_search: SemanticSearch;
  training_data: TrainingData;
}

/**
 * Interface for image search results from the database.
 */
export interface ImageSearchResult {
  id: number;
  uuid: string;
  filePath: string;
  fileName: string | null;
  szName?: string | null;
  szTagRefs?: string[];
  createdAt: string;
  description: string;
  keywords: string[];
  tags: string[];
  qwenCaptions: Record<string, any> | string[];
  yoloObjects: string[];
  similarity?: number;
}

export type DtcFetchMode = 'upload' | 'path';

export interface DtcTaskItem {
  task_id: string;
  mode: DtcFetchMode;
  status: 'queued' | 'running' | 'success' | 'failed';
  queue_index?: number;
  prompt: string;
  threshold: number;
  input_path: string;
  output_base: string;
  error?: string | null;
  created_at?: string;
  updated_at?: string;
  started_at?: string | null;
  finished_at?: string | null;
  result_count?: number;
}

export interface DtcResultItem {
  sourceName: string;
  imageName?: string;
  imagePath?: string;
  jsonName?: string;
  jsonPath?: string;
  resultJson: Record<string, any>;
}

export interface DtcFetchResponse {
  success: boolean;
  task?: DtcTaskItem;
  results: DtcResultItem[];
  error?: string;
}
